language: python
python:
  - "3.6.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script: 
  - cd seidart-gui/gui/tests
  - sudo apt install gfortran
script: pytest
